import "./globals.css";

import type { Metadata } from "next";

import { cn } from "@/lib/core/utils";
import Navbar from "@/components/layouts/Navbar";
import { clashDisplay, montserrat, unicaOne } from "@/lib/core/constants/fonts";

export const metadata: Metadata = {
  title: "GetLinked",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme='dark' lang='en' className='dark bg-primary-bg'>
      <body
        className={cn(
          clashDisplay.variable,
          montserrat.variable,
          unicaOne.variable,
          montserrat.className,
          "text-white"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
