import Navbar from "@/components/layouts/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { clashDisplay, montserrat } from "@/lib/core/constants/fonts";
import { cn } from "@/lib/core/utils";

export const metadata: Metadata = {
  title: "GetLinked",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme='dark' lang='en' className='dark bg-primary-bg'>
      <body
        className={cn(
          clashDisplay.variable,
          montserrat.variable,
          montserrat.className
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
